name: search_page
description: Fast and easy way to build a custom search experience in you app
version: 2.3.0
homepage: https://github.com/jesusrp98/search_page

environment:
  flutter: '>=3.3.0'
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: '>=3.0.0 <4.0.0'
